language: generic 
sudo: required

# Need a copy of Docker running
services:
  - docker 

# Build our image using Dockerfile.dev
before_install:
  - docker build -t cinesia/docker-react -f Dockerfile.dev .

# Run our test suite
script:
  # docker run <tag-image> <override-run-command>
  - docker run -e CI=true cinesia/docker-react npm run test

# Deploy to some hosting service
deploy:
  provider: elasticbeanstalk # preconfigured in travis
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-162578366392"
  bucker_path: "docker-react"
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY