language: generic 
sudo: required

# Need a copy of Docker running
services:
  - docker 

# Build our image using Dockerfile.dev
before_install:
  - docker build -t cinesia/docker-react -f Dockerfile.dev .

# Run our test suite
script:
  # docker run <tag-image> <override-run-command>
  - docker run -e CI=true cinesia/docker-react npm run test
  # - docker run cinesia/docker-react npm run test -- --coverage


# Deploy to some hosting service
deploy:
  provider: azure_web_apps
#   username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
#   password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
#   site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
#   slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set